Client Starter
icecube/skymap_scanner pull request #123
Opened 2023-01-30 23:02 UTC by ric-evans

A resource script for spawning clients on a condor cluster

see https://github.com/WIPACrepo/SkyDriver/issues/5

2023-01-31 16:57 UTC, ric-evans commented
fsdfsdf
ssdsd

2023-01-31 20:36 UTC, ric-evans commented
sdfsdf

2023-02-06 17:41 UTC, dsschult requested changes
Generally looks good.  My only comment is that it would be nice to have a mode where the collector/schedd was filled in from local host values, so it could connect automatically for someone like Tianlu.  But it would probably work as-is.

2023-02-06 17:41 UTC, dsschult commented on resources/client_starter.py
> +    schedd = get_schedd(args.collector_address, args.schedd_name)
the args are called `collector` and `schedd`.  maybe they need to be renamed?

2023-02-06 18:21 UTC, ric-evans commented
> Generally looks good. My only comment is that it would be nice to have a mode where the collector/schedd was filled in from local host values, so it could connect automatically for someone like Tianlu. But it would probably work as-is.

I'm thinking that's what will happen when the CL args are not given (`""`)

2023-02-06 19:46 UTC, dsschult approved these changes

2023-02-06 21:48 UTC, merged